# Generated by Django 4.2.7 on 2023-12-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardquest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='col_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='collection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='trainer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
